name: highcharts
version: 0.5.0+2
author: Gonzalo Pezzi <gonzalopezzi@gmail.com>
description: Highcharts API wrapped via JS interop (js package).
homepage: https://github.com/gonzalopezzi
environment:
  sdk: ">=1.8.0 <2.0.0"
dependencies:
  uuid: '>=0.5.0 <0.6.0'
  js: "^0.6.0"
dev_dependencies:
  unittest: any
